apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liman.fullname" . }}-beat
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "liman.labels" . | nindent 4 }}
    app.kubernetes.io/component: beat
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "liman.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: beat
  template:
    metadata:
      labels:
        {{- include "liman.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: beat
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: beat
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - clinic
            - beat
            - --loglevel=info
          envFrom:
            - configMapRef:
                name: {{ include "liman.fullname" . }}-config
            - secretRef:
                name: {{ .Values.externalSecret.name }}
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
