apiVersion: v1
kind: Service
metadata:
  name: {{ include "liman.fullname" . }}-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "liman.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "liman.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
