apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clinic-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io
      chart: limanalhassan/clinic
      targetRevision: 0.1.5
      helm:
        valueFiles:
          - $values/argocd_application/values/clinic/values.yaml
    - repoURL: git@github.com:limanalhassan/clinic_appointment_app.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: clinic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
