apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: albN
spec:
  scheme: internet-facing
  group:
    name: liman-app
  certificateARNs:
    - arn:aws:acm:ca-central-1:316865756768:certificate/07627e8c-20cf-48d4-b62f-4c5f1ccb7151

---

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: albN
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: albN
