apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clinic.fullname" . }}-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clinic.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "clinic.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "clinic.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - clinic
            - worker
            - --loglevel=info
            - --concurrency=4
          envFrom:
            - configMapRef:
                name: {{ include "clinic.fullname" . }}-config
            - secretRef:
                name: {{ .Values.externalSecret.name }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
